kindergarden/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template, redirect_to
from django.views.static import serve
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from gardens.context_processors import statistics
import gardens.views as views
import kindergarden.settings as settings

admin.autodiscover()

urlpatterns = patterns('',
    (r'^$', redirect_to, {'url' : '/home/'}),
    (r'^home/$', views.home),

    (r'^choose/$', views.choose),
    
    #list of gardens
    (r'^kindergardens/$', views.kindergardens),
    
    #garden details
    (r'^kindergardens/(?P<id>\d+)/$',  views.garden_details),
    
    #article
    (r'^article/(?P<id>\d+)/$',  views.article),
    

    (r'^comments/', include('django.contrib.comments.urls')),

    
#-----------------ADMIN------------------------------------------------------------------------------------------ 

    # Example:
    # (r'^kindergarden/', include('kindergarden.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
)

gardens/models.py
# -*- coding: utf8 -*-

from django.db import models
import json

class Kindergarden(models.Model):
    name = models.CharField(u'Название детского сада', max_length=200)
    lng = models.FloatField('Долгота в градусах')
    lat = models.FloatField('Широта в градусах')
    address = models.CharField('Адрес', max_length=200)
    telephone = models.CharField('Телефон', max_length=200)
    rst_description = models.TextField('Описание сада в формате RST')
    
    def js_lat(self):
        return json.dumps(self.lat)
        
    def js_lng(self):
        return json.dumps(self.lng)
        
    
    def __unicode__(self):
        return unicode(self.name)
        

class Gallery(models.Model):
    image = models.FileField('Изображение', upload_to='.')
    kindergarden = models.ForeignKey(Kindergarden, verbose_name='Для какого детского сада')
    description = models.TextField('Описание фотографии')
    
    def __unicode__(self):
        return self.image.name

class User(models.Model):
    login = models.CharField('Логин', max_length=200)
    password = models.CharField('Пароль', max_length=200)
    admin = models.BooleanField('Админь?')

    def __unicode__(self):
        return self.login

class Article(models.Model):
    kindergarden = models.ForeignKey(Kindergarden, verbose_name='Для какого детского сада')
    title = models.CharField('Заголовок', max_length=1000)
    rst_content = models.TextField('Содержание статьи в формате RST')

    def __unicode__(self):
        return self.title
    
class GalleryComment(models.Model):
    user = models.ForeignKey(User, verbose_name='Пользователь')
    gallery = models.ForeignKey(Gallery, verbose_name='К какой фотографии')
    rst_comment = models.TextField('Комментарий в формате RST')
    
    def __unicode__(self):
        return u"{0} | {1}".format(self.user, self.gallery)
    
class ArticleComment(models.Model):
    user = models.ForeignKey(User, verbose_name='Пользователь')
    article = models.ForeignKey(Article, verbose_name='К какой статье')
    rst_comment = models.TextField('Комментарий в формате RST')

    def __unicode__(self):
        return u"{0} | {1}".format(self.user, self.article)

# Create your models here.

gardens/forms.py
#-*- coding: utf-8 -*-
'''
Created on 07.12.2010

@author: Dmitry
'''

import django.forms as forms

class LoginForm(forms.Form):
    login = forms.CharField(widget = forms.TextInput(attrs={'size':'14'}))
    password = forms.CharField( widget = forms.PasswordInput(attrs={'size':'14'}) )
    
class Comment(forms.Form):
    content = forms.CharField()
    
class Register(forms.Form):
    login = forms.CharField()
    password = forms.CharField()
    
class AddEditArticle(forms.Form):
    title = forms.CharField()
    rst_content = forms.CharField()
    
class AddEditGarden(forms.Form):
    pass

gardens/views.py
# -*- encoding: utf8 -*-
# Create your views here.


from django.http import HttpResponse
from django.shortcuts import render_to_response
from django.views.generic.list_detail import object_detail, object_list
from django.template import RequestContext 
from gardens.context_processors import statistics

import models
import forms
import json



def home(request):
    return render_to_response('home.html', context_instance=RequestContext(request))

def choose(request):
    coord = []
    for g in models.Kindergarden.objects.all():
        coord.append( {"g_id": g.id, "coord" : [g.lng, g.lat], "name" : g.name } )
    return render_to_response('choose.html', dictionary={"coord" : json.dumps(coord)}, context_instance=RequestContext(request))

def garden_details(request, id):
    return object_detail(request, models.Kindergarden.objects.all(), object_id=id, template_name='garden_details.html')

def kindergardens(request):
    return object_list(request=request, queryset=models.Kindergarden.objects.all(), template_name='kindergardens.html')

def article(request, id):
    return object_detail(request, models.Article.objects.all(), object_id=id, template_name='article.html')

def admin_garden_list(request):
    return object_list(request, models.Kindergarden.objects.all(), template_name='admin/garden_list.html')

def admin_article_list(request):
    return object_list(request, models.Article.objects.all(), template_name='admin/article_list.html')

def admin_user_list(request):
    return object_list(request, models.User.objects.all(), template_name='admin/user_list.html')

# forms
def admin_garden_add(request):
    return render_to_response('admin/garden_add_form.html', context_instance=RequestContext(request))

def admin_user_add(request):
    return render_to_response('admin/user_add_form.html', context_instance=RequestContext(request))


def admin_article_add(request):
    
    form = forms.AddEditArticle()
    return render_to_response('admin/article_add_form.html', {'form' : form}, context_instance=RequestContext(request))


def admin_garden_edit(request, id):
    pass

def admin_user_edit(request, id):
    pass

def admin_article_edit(request, id):
    pass

templates/admin.html
{% extends "base.html" %}

{% block section %}
Админка
{% endblock section %}

{% block content %}

<div class="span-20 last">

<div id="admin_menu">
<a href="/admin/garden_list/" class="button">Детские сады</a>
<a href="/admin/user_list/" class="button">Управление пользователями</a>
<a href="/admin/article_list/" class="button">Статьи</a>
<a href="/" class="button">Галереи</a>
</div>

</div>

<div class="span-20 last">
<div id="admin_content" class="box">
{% block admin_content %}

Выберете пункт

{% endblock admin_content %}
</div>
</div>

{% endblock content %}
   

templates/article.html
{% extends "base.html" %}
{% load markup %}

{% block section %}
	Статьи
{% endblock section %}

{% block content %}
<div class="box">
	<h4>{{ object.kindergarden.name }}</h4>
	<h5>{{ object.title }}</h5>
	{{ object.rst_content|restructuredtext }}

</div>
{% endblock content %}

templates/base.html

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Детские сады</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="/site_media/css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
    </style>
    <link href="/site_media/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/site_media/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/site_media/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/site_media/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="/site_media/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="/site_media/ico/favicon.png">
  </head>

  <body>

    <div class="navbar  navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/home/#">Детские сады</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li id="active_home_id"><a href="/home/">Дом</a></li>
              <li id="active_kindergardens_id"><a href="/kindergardens/">Список садов</a></li>
              <li id="active_choose_id"><a href="/choose/">Выбор сада</a></li>
              <li id="active_admin_id"><a href="/admin/">Админка</a></li>
            </ul>
          
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

 

      <!-- Example row of columns -->
      <div class="row">
        <div class="span8">
     	{% block content %}
		{% endblock content %}
        </div>
        <div class="span4">
       {% block statistics %}
<h4 class="caps">Статистика</h4>
Детских садов: {{ gardens_count }}<br />
Статей: {{ article_count }}<br />
Комментариев: {{ comment_count }}<br />
Пользователей: {{ user_count }}<br />
{% endblock statistics %}
       </div>
      
      </div>

      <hr>

      <footer>
      	{% block bottom %}
			<span class="quiet">© 2010, 2012 Краюшкин Дмитрий</span>
			<br />
			<span class="quiet">Пишите: </span>
			<a href="mailto:krayushkin.dm@gmail.com">krayushkin.dm@gmail.com</a><br />
		{% endblock bottom %}
      </footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/site_media/js/jquery.js"></script>
    <script src="/site_media/js/bootstrap.js"></script>
    <!--
    <script src="/site_media/js/bootstrap-alert.js"></script>
    <script src="/site_media/js/bootstrap-modal.js"></script>
    <script src="/site_media/js/bootstrap-dropdown.js"></script>
    <script src="/site_media/js/bootstrap-scrollspy.js"></script>
    <script src="/site_media/js/bootstrap-tab.js"></script>
    <script src="/site_media/js/bootstrap-tooltip.js"></script>
    <script src="/site_media/js/bootstrap-popover.js"></script>
    <script src="/site_media/js/bootstrap-button.js"></script>
    <script src="/site_media/js/bootstrap-collapse.js"></script>
    <script src="/site_media/js/bootstrap-carousel.js"></script>
    <script src="/site_media/js/bootstrap-typeahead.js"></script>
    -->
    {% block js_code %}
    {% endblock js_code %}

  </body>
</html>



templates/choose.html
{% extends "base.html" %}

{% block js_code %}
<script src="http://api-maps.yandex.ru/2.0-stable/?load=package.full&lang=ru-RU" type="text/javascript"></script>

  <script type="text/javascript">

    

        // Создает обработчик события window.onLoad
        $(function () {
            
    $("#active_choose_id").addClass("active");
});
      

/*
Широта: 54°9′17.56″N (54.154878)
Долгота: 48°5′37.22″E (48.093673)

Широта: 54°27′7.34″N (54.452039)
Долгота: 48°45′0.38″E (48.750106)

var bounds = new YMaps.GeoBounds(
    new YMaps.GeoPoint(54.154878, 48.093673),
    new YMaps.GeoPoint(54.452039, 48.750106));


*/
        // Создает обработчик события window.onLoad
function start_geo()
{
    var addr = $('#id_address').val();
    bounds = [[54.154878, 48.093673], [54.452039, 48.750106]];

    var geocoder = new ymaps.geocode(addr, {boundedBy : bounds, strictBounds: true});
    geocoder.then(
    function (res) {
    if (res.geoObjects.getLength()) {
        show_table(res.geoObjects.get(0));
    } else {
        alert("Ничего не найдено")
    }
}, 

function (err){
    alert("Произошла ошибка: " + err);
}

);
 
   
                    
                
  }


function show_table(home)
{

                var g = {{coord|safe}};
                var near = [];
                var radius = 1000;
                for (i in g)
                {
                    var geo_point = new ymaps.Placemark(
                        [g[i]["coord"][1], g[i]["coord"][0]]
                        );
                    var home_coord = home.geometry.getCoordinates();
                    var distance =  ymaps.coordSystem.geo.getDistance(geo_point.geometry.getCoordinates(), home_coord);
                    if (distance < radius)
                    {
                        g[i]["distance"] = Math.round(distance);
                        g[i]["geo_point"] = geo_point;
                        near.push(g[i]);
                    } 
                }
                
                near.sort(function(a,b)
                    {
                        return a['distance'] - b['distance'];
                        } );
         

         
                $('#table_div_id').empty();
                $('#ymap').empty();
        $('<table id="tbl" class="table table-striped table-bordered"></table>').appendTo('#table_div_id');


         $('#tbl').append("<thead><th>Детский сад</th><th>Расстояние в метрах</th></thead>");

        var map = new ymaps.Map("ymap", {center: home.geometry.getCoordinates(), zoom: 17});


        map.behaviors.enable('scrollZoom');
        home.options.set("preset",'twirl#redDotIcon');

        map.geoObjects.add(home);
        


         near.forEach(function(i)
         {
            var geo_point = i["geo_point"];
            geo_point.properties.set("balloonContentHeader", i["name"]);
            geo_point.properties.set("balloonContentBody", "Расстояние от дома: <strong>" + i["distance"]+ "</strong> метров");

            
            map.geoObjects.add(geo_point);
	    

            $("#tbl").append("<tr><td><a href=\"/kindergardens/" + i["g_id"] +"/\" >" + i["name"] + "</a></td><td> <span class='large'>" + i["distance"] +  "</span></td</tr>");
          }); 

         map.setBounds(map.geoObjects.getBounds());
        var myCircle = new ymaps.Circle([home.geometry.getCoordinates(), radius]);
        myCircle.options.set('fillOpacity', 0.1);
        map.geoObjects.add(myCircle);
         


}


    </script>
 
{% endblock js_code %}



{% block section %}
Выбор
{% endblock section %}

{% block content %}

<p>Введите улицу и дом где вы живете и найдите ближайшие детские садики в радиусе 1 км</p>
    <form class="form-inline" onsubmit="return false;">
    <p><label for="id_address">Адрес:</label>
    <input id="id_address" type="text" name="address"  /></p><p>
    <button type="submit" class="btn btn-primary btn-large" onclick="start_geo();">Найти</button> </p>
    </form>
    

    <div id="table_div_id">
    </div>
<div id="ymap" style="width:300px;height:300px">

    </div>

{% endblock content %}
   

templates/garden_details.html
{% extends "base.html" %}
{% load markup %}
{% load comments %}

{% block js_code %}
    <script src="http://api-maps.yandex.ru/2.0-stable/?load=package.full&lang=ru-RU" type="text/javascript"></script>
  <script type="text/javascript">

 
     // Создает обработчик события window.onLoad
    ymaps.ready(function () {

    var map = new ymaps.Map('YMapsID', { center: [{{ object.js_lat}}, {{ object.js_lng }}], zoom: 17 });
    map.behaviors.enable('scrollZoom');
    // Создает метку, значок которой не скрывается при открытии балуна
    var placemark = new ymaps.Placemark([{{ object.js_lat}}, {{ object.js_lng }}]);
    // Добавляет метку на карту
    map.geoObjects.add(placemark);
    });







    </script>
 
{% endblock js_code %}


{% block section %}
	Детали
{% endblock section %}

{% block content %}

	<h4>{{ object.name }}</h4>
	
		
	
	<strong>Адрес: </strong>{{ object.address }}<br />
	<strong>Телефон: </strong>{{object.telephone }}<br />
	<strong>Расположение на карте: </strong><br />
		<div id="YMapsID" style="width:300px;height:200px"></div>
	
	<h5>Статьи</h5>
	<ul class="large">
		{% for article in object.article_set.all %}
                <li>
                    <a href="/article/{{ article.id }}">{{ article.title }}</a>
                </li>
                {% empty %}
                    <li>Статей нет</li>    
                {% endfor %}
            </ul>
	<h5>Описание</h5>
	{{ object.rst_description|restructuredtext}}


<h5>Комментарии</h5>

    {% get_comment_count for object as comment_count %}
    {% if comment_count %}
        {% render_comment_list for object %}
    {% else %}
        Нет комментариев
    {% endif %}


    <h5>Оставить комментарий</h5>
    {% render_comment_form for object %}
	


{% endblock content %}

templates/home.html
{% extends "base.html" %}

{% block js_code %}
  <script type="text/javascript">

        // Создает обработчик события window.onLoad
        $(function () {
            
	$("#active_home_id").addClass("active");
});
        </script>

{% endblock js_code %}

{% block content %}






  
  <h1>Привет!</h1>
  <p>Сервис поможет выбрать ближайший детский садик</p>
  <p>
    <a class="btn btn-primary btn-large" href="/choose/">
      Выбрать
    </a>
  </p>







{% endblock content %}



templates/kindergardens.html
{% extends "base.html" %}

{% block js_code %}
  <script type="text/javascript">

        // Создает обработчик события window.onLoad
        $(function () {
            
	$("#active_kindergardens_id").addClass("active");
});
        </script>

{% endblock js_code %}

{% block content %}



    <table class="table table-striped table-bordered">
<thead>
<th>Детский садик</th>
<th>Где находится</th>
</thead>
{% for garden in object_list %}

             

	<tr>

<td>
	<a href="/kindergardens/{{ garden.id }}">{{ garden.name }}</a>
</td>
<td>
	{{ garden.address }}
</td>

</tr>

{% endfor %}

	</table >

{% endblock content %}
  

templates/map.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Примеры. Простой вызов карты.</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <script src="http://api-maps.yandex.ru/1.1/index.xml?key=ANpUFEkBAAAAf7jmJwMAHGZHrcKNDsbEqEVjEUtCmufxQMwAAAAAAAAAAAAvVrubVT4btztbduoIgTLAeFILaQ==" type="text/javascript"></script>
    <script type="text/javascript">

    
arr = [
{"name":"111","ll":[48.331882,54.259784]},
{"name":"211","ll":[48.332182,54.259137]},
{"name":"173","ll":[48.332669,54.253626]},
{"name":"151","ll":[48.332229,54.25269]},
{"name":"156","ll":[48.326168,54.251879]},
{"name":"166","ll":[48.325781,54.251389]},
{"name":"215","ll":[48.322938,54.254939]},
{"name":"157","ll":[48.327509,54.258224]},
{"name":"256","ll":[48.386358,54.356944]},
{"name":"112","ll":[48.393664,54.345758]},
{"name":"2","ll":[48.390955,54.32934]},
{"name":"105","ll":[48.384102,54.321258]},
{"name":"104","ll":[48.345185,54.304796]},
{"name":"107","ll":[48.354691,54.308127]},
{"name":"112","ll":[48.367782,54.287245]},
{"name":"115","ll":[48.330991,54.257735]},
{"name":"123","ll":[48.318778,54.295795]},
{"name":"ромашка","ll":[48.277188,54.421259]},
{"name":"березка","ll":[48.273379,54.422955]},
{"name":"вишенка (примерно)","ll":[48.258048,54.43332]}
]


    
        // Создает обработчик события window.onLoad
        YMaps.jQuery(function () {
        	var map = new YMaps.Map(YMaps.jQuery("#YMapsID")[0]);
        	 map.enableScrollZoom();
        	 map.setType(YMaps.MapType.SATELLITE);
        	for (var i = 0; i < arr.length; i++)
        		{
        		// Создает метку, значок которой не скрывается при открытии балуна
        		var placemark = new YMaps.Placemark(new YMaps.GeoPoint(arr[i].ll[0], arr[i].ll[1]), {hideIcon: false});

        		// Добавляет метку на карту
        		map.addOverlay(placemark);
        		}
        	
        	
        	map.setCenter(new YMaps.GeoPoint(48.386358,54.356944), 12);
        })
    </script>
</head>

<body>
    <div id="YMapsID" style="width:600px;height:400px"></div>
</body>

</html>